spring:
  application:
    name: cars-soap-service

  webservices:
    wsdl-locations: classpath:META-INF/schemas/

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cars_db
    username: postgres
    password: Beka04

  jpa:
    show-sql: true